repos:
- repo: local
  hooks:
    - id: terraform_fmt
      name: Terraform Format
      description: Rewrites Terraform configuration files to a canonical format and style.
      entry: terraform fmt -recursive
      language: system
      pass_filenames: false
      files: (\.tf|\.tfvars)$
      exclude: \.terraform\/.*$

    - id: terraform_init
      name: Terraform Init
      description: Initializes a working directory containing Terraform configuration files.
      entry: terraform init -backend=false -upgrade
      language: system
      pass_filenames: false
      files: (\.tf|\.tfvars)$
      exclude: \.terraform\/.*$

    - id: terraform_validate
      name: Terraform Validate
      description: Validates the configuration files.
      entry: terraform validate
      language: system
      pass_filenames: false
      files: (\.tf|\.tfvars)$
      exclude: \.terraform\/.*$

    - id: tflint
      name: TFLint
      description: Finds possible errors (like illegal instance types) for Major Cloud providers (AWS/Azure/GCP), warns about deprecated syntax, unused declarations, enforces best practices, naming conventions.
      require_serial: true
      entry: tflint --format compact
      language: system
      pass_filenames: false
      files: (\.tf|\.tfvars)$
      exclude: \.terraform\/.*$

    - id: terraform_full_docs
      name: Terraform Full Docs
      description: Generates documentation from Terraform modules in various output formats.
      require_serial: true
      entry: terraform-docs -c .terraform-full-docs.yml .
      language: system
      pass_filenames: false
      files: (\.tf|\.terraform\.lock\.hcl)$
      exclude: \.terraform\/.*$

    - id: terraform_partial_docs
      name: Terraform Partial Docs
      description: Generates documentation from Terraform modules in various output formats.
      require_serial: true
      entry: terraform-docs -c .terraform-partial-docs.yml .
      language: system
      pass_filenames: false
      files: (\.tf|\.terraform\.lock\.hcl)$
      exclude: \.terraform\/.*$

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.3.0
  hooks:
    - id: end-of-file-fixer
      name: End of line fixer
      description: Ensures that files is either empty, or ends with one newline.
    - id: trailing-whitespace
      name: Trailing whitespace
      description: Trims trailing whitespace.
    - id: mixed-line-ending
      name: Mixed Line Ending
      description: Replaces or checks mixed line ending.
      args: ['--fix=lf']
