name: Terraform

on:
  pull_request:
    paths:
      - '**.tf'

jobs:
  terraform:
    name: Terraform
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Terraform Format
        run: terraform fmt -check -recursive

      - name: Terraform Init
        run: terraform init -backend=false -upgrade

      - name: Terraform Validate
        run: terraform validate -no-color

      - name: Setup TFLint
        uses: terraform-linters/setup-tflint@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Run TFLint
        run: tflint --format compact

      - name: Run TFSec
        uses: aquasecurity/tfsec-pr-commenter-action@main
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Run Terrascan
        uses: accurics/terrascan-action@main
        with:
          iac_type: 'terraform'
          scm_token: ${{ secrets.GITHUB_TOKEN }}
          sarif_upload: true
